
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgqjtpjfemnlispkfmsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpncWp0cGpmZW1ubGlzcGtmbXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjUyMTUsImV4cCI6MjA1ODA0MTIxNX0.tm-W5TjaLW6UXUjSISq-NCqWBCBU63gCLeTXm2A3flI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check if Supabase is connected
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('contacts').select('count');
    if (error) {
      console.error('Supabase connection error:', error);
      return false;
    }
    return true;
  } catch (err) {
    console.error('Supabase client error:', err);
    return false;
  }
};
